spring:
  application:
    name: ai-passage-creator
  profiles:
    active: local
  # ? ???? Session
  session:
    redis:
      # ??????JSON
      serializer: json
      flush-mode: on-save
    # session 30 ???
    timeout: 2592000
  # MySQL ???????????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_passage_creator
    username: root
    password: 114514
  # Redis ????????
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:

mybatis-flex:
  configuration:
    map-underscore-to-camel-case: false

server:
  port: 8341
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi ??
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.kanade.aipassage.controller